[package]
name = "callbacks"
version = "0.1.0"
edition = "2024"

[dependencies]
rwf = {path = "../../rwf"}
tokio = {version = "1.49.0", features = ["full"]}
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"