[package]
name = "openapi"
version = "0.1.0"
edition = "2024"

[dependencies]
rwf = {path = "../../rwf"}
tokio = { version = "1", features = ["full"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1.0.149"
serde_norway = "0.9.42"