[package]
name = "django"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rwf = { path = "../../rwf", features = ["wsgi"] }
tokio = { version = "1", features = ["full"] }
pyo3 = "0.22"
tracing = "0.1"
